name: "Python to DB Scraper"
description: "Starts a docker container with Python to connect to our GdK DB"
inputs:
  PG_SERVER:
    description: The server where the PG DB lives
    required: true
  PG_PORT:
    required: true
    default: 5432
  PG_USER:
    required: true
    description: ""
  PG_PASS:
    required: true
    description: ""
  PG_DB:
    required: true
    description: ""
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    PG_DB: ${{ inputs.PG_DB }}
    PG_PASS: ${{ inputs.PG_PASS }}
    PG_PORT: ${{ inputs.PG_PORT }}
    PG_SERVER: ${{ inputs.PG_SERVER }}
    PG_USER: ${{ inputs.PG_USER }}
