name: "Giess den Kiez Open Data Script"

on:
  push:
    branches:
      - main
 # schedule:
#  - cron: "*/10 * * * *"
    
jobs:
  start-docker-container:
    runs-on: ubuntu-latest
    name: A job to start the docker container
    steps:
      - name: get the action
        uses: actions/checkout@v2
      - name: run Python script
        uses:
        with:
          PG_DB: ${{ secrets.PG_DB }}
          PG_PASS: ${{ secrets.PG_PASS }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_SERVER: ${{ secrets.PG_SERVER }}
          PG_USER: ${{ secrets.PG_USER }}
