name: Datenregister Dataset Update
on:
  push:
    branches:
      - main
    paths:
      - "daten/giessdenkiezKPIs.csv"
      - "daten/giessdenkiez_bewässerungsdaten.csv"
      - "daten/giessdenkiez_bewässerungsdaten.geojson"
      - "daten/test.csv"
env:
  CKAN_TOKEN: ${{secrets.CKAN_TOKEN}}
jobs:
  dataset_update:
    runs-on: ubuntu-latest
    name: Dataset Update
    steps:
      - name: Do not run on template repository
        shell: bash
        run: |
          curl https://api.github.com/repos/$GITHUB_REPOSITORY \
            | jq --exit-status '.is_template == false'
      # check out this repo
      - uses: actions/checkout@v4
      - name: Install Requirements
        run: |
          pip install -r requirements.txt
          pip install git+https://github.com/berlinonline/ckan_metadata_updater
      - name: Run Updater
        run: |
          make dataset-update
