name: "Giess den Kiez Open Data Script"

on:
  push:
    branches:
      - main
 # schedule:
#  - cron: "*/10 * * * *"
    
jobs:
  start-docker-container:
    environment: Connections
    runs-on: ubuntu-18.04
    name: A job to start the docker container
    steps:
      - name: get the action
        uses: actions/checkout@v2
      - name: see env variables
        run: env
      - name: where am I?
        run: ls -a
      - name: Python action
        uses: ./
        id: scraper
        with:
          PG_SERVER: ${{ secrets.PG_SERVER }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASS: ${{ secrets.PG_PASS }}
          PG_DB: ${{ secrets.PG_DB }}
